(setq mew-name "Kuroi Mato")
(setq mew-from "venmos@fuck.gfw.es")
(setq mew-mail-path "~/.emacs.d/email")
(setq mew-conf-path mew-mail-path)
(setq mew-addrbook-file "~/.emacs.d/mew.addrbook")
(setq mew-ssl-verify-level 0)
;; GPG
(setq mew-prog-pgp "gpg")
(setq mew-prog-gpg "gpg-emacs")
;; IMAP for Gmail
(setq mew-use-cached-passwd t)
(setq mew-use-master-passwd t)
(setq mew-proto "%")
(setq mew-imap-server "imap.gmail.com")
(setq mew-imap-user "venmos@fuck.gfw.es")
(setq mew-imap-auth  t)
(setq mew-imap-ssl t)
(setq mew-imap-ssl-port "993")
(setq mew-smtp-auth t)
(setq mew-smtp-ssl t)
(setq mew-smtp-ssl-port "465")
(setq mew-smtp-user "venmos@fuck.gfw.es")
(setq mew-smtp-server "smtp.gmail.com")
(setq mew-fcc "%Sent")
(setq mew-imap-trash-folder "%[Gmail]/已删除邮件")
(setq mew-use-cached-passwd t)
(setq mew-ssl-verify-level 0)
;; Code
(setq mew-charset-m17n "utf-8")
(setq mew-internal-utf-8p)
